version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: safexpress
    container_name: safexpress-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - safexpress

  db:
    image: mysql:8.0
    container_name: safexpress-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_database
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - safexpress

  nginx:
    image: nginx:1.17-alpine
    container_name: safexpress-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - safexpress

networks:
  safexpress:
    driver: bridge
