version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: safexpress
    container_name: safexpress-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - safexpress

  mysql:
    image: mysql:8.0
    container_name: safexpress-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - safexpress

  nginx:
    image: nginx:alpine
    container_name: safexpress-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    #   - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # depends_on:
    #   - php
    #   - mysql
    networks:
      - safexpress

#   php:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: php
#     volumes:
#       - .:/var/www/html
#     ports:
#       - "9000:9000"
#     networks:
#       - safexpress

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - app
    networks:
      - safexpress

networks:
  safexpress:
    driver: bridge
