version: "3.8"
services:
    api:
        container_name: Safexpress
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 80:80
    #     depends_on:
    #         - database
    #         - redis
    # database:
    #     container_name: database
    #     image: mysql:8.0
    #     ports:
    #         -   3306:3306
    #     environment:
    #         - MYSQL_DATABASE=${DB_DATABASE}
    #         - MYSQL_USER=${DB_USERNAME}
    #         - MYSQL_PASSWORD=${DB_PASSWORD}
    #         - MYSQL_ROOT_PASSWORD=${DB_DATABASE}
    #     volumes:
    #         - db-data:/var/lib/mysql
    # redis:
    #     container_name:  redis
    #     image: redis:alpine
    #     command: redis-server --appendonly yes --requirepass  "secret"
    #     ports:
    #         - 6380:6379
    # node:
    #     build:
    #         context: .
    #         target: node
    #     volumes:
    #         - .:/usr/src
    #         - ./node_modules:/usr/src/node_modules
    #     tty: true
volumes:
    db-data: ~
