version: '3'

networks:
  webapp:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
       - .:/var/www
    ports:
       - "80:80"
    networks:
      - webapp

