version: '3'

networks:
  webapp:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
    - "80:80"
    links:
      - php
    volumes:
      - .:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
    networks:
      - webapp

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
       - .:/var/www
    ports:
       - "9001:9000"
    networks:
      - webapp

