version: "3.8"
services:

    database:
        container_name: database
        image: mysql:8.1
        ports:
            -   3306:3306
        environment:
            MYSQL_DATABASE: db_safexpress
            MYSQL_USER: root
            MYSQL_PASSWORD=: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - db-data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
         - 9001:80
        environment:
         - PMA_ARBITRARY=1

volumes:
    db-data: ~
