version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db_safexpress
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"